CREATE TABLE SCHOOL (
	NUM INT PRIMARY KEY,
    S_NAME VARCHAR(50),
    AREA VARCHAR(50),
    COURSE_CNT INT,
    C_DATE DATETIME
);

CREATE TABLE COURSE01 (
	NUM INT PRIMARY KEY,
    SCHOOL_NUM INT,
    C_NAME VARCHAR(15),
    STUDENT_CNT INT,
    C_DATE DATETIME,
    FOREIGN KEY (SCHOOL_NUM) REFERENCES SCHOOL(NUM) ON DELETE SET NULL
);


CREATE TABLE NOODLE (
NUM INT
, NAME VARCHAR(50)
, COMPANY VARCHAR(10)
, KIND VARCHAR(1)
, PRICE INT
, E_DATE DATETIME
);