INSERT INTO SCHOOL VALUES (1, '서울대학교','서울',35,'1980-07-01');
INSERT INTO SCHOOL VALUES (2, '중앙대학교', '서울',27, '1981-08-01');
INSERT INTO SCHOOL VALUES (3, '동아대학교','부산',32,'1982-09-01');
INSERT INTO SCHOOL VALUES (4, '부산대학교','부산',21,'1983-09-01');


INSERT INTO COURSE01 VALUES (1, 4,'IT',50,'2000-07-09');
INSERT INTO COURSE01 VALUES (2, 3,'경영',60,'2010-08-09');
INSERT INTO COURSE01 VALUES (3,2,'식품영양',70,'2008-04-09');
INSERT INTO COURSE01 VALUES (4, 1,'화학',80,'2007-07-09');


SELECT * FROM SCHOOL;
SELECT * FROM COURSE01;

SELECT * FROM SCHOOL WHERE AREA = '부산';
SELECT * FROM SCHOOL WHERE COURSE_CNT >=26 AND COURSE_CNT <=30;
SELECT * FROM SCHOOL WHERE COURSE_CNT BETWEEN 26 AND 30;
SELECT * FROM SCHOOL WHERE S_NAME LIKE '%서울%' AND AREA LIKE '%서울%';
SELECT * FROM SCHOOL WHERE C_DATE LIKE '%-08-%';
SELECT * FROM SCHOOL WHERE MONTH(C_DATE) = 8;

SELECT * FROM COURSE01 WHERE C_NAME LIKE '%영%';
SELECT * FROM COURSE01 WHERE STUDENT_CNT >=60;
SELECT * FROM COURSE01 WHERE C_DATE < '2002-04-01';
SELECT * FROM COURSE01 WHERE C_DATE LIKE '__-__-__';
SELECT date_format(C_DATE, '%y-%m-%d') as C_DATE FROM COURSE01;





INSERT INTO NOODLE VALUES (
1, '안성탕면', '농심', 'M', 700, NOW() + INTERVAL 3 MONTH);
INSERT INTO NOODLE VALUES (
1, '김치라면', '삼양', 'M', 700, NOW() + INTERVAL 3 MONTH);
INSERT INTO NOODLE VALUES (
1, '진라면', '오뚜기', 'C', 800, NOW() + INTERVAL 3 MONTH);
INSERT INTO NOODLE VALUES (
1, '꼬꼬면', '팔도', 'C', 1000, NOW() + INTERVAL 3 MONTH);
INSERT INTO NOODLE VALUES (
2, '신라면', '농심', 'C', 1100, NOW() + INTERVAL 3 MONTH);
INSERT INTO NOODLE VALUES (
2, '삼양라면', '삼양', 'M', 700, NOW() + INTERVAL 3 MONTH);
INSERT INTO NOODLE VALUES (
3, '너구리', '농심', 'M', 850, NOW() + INTERVAL 3 MONTH);
INSERT INTO NOODLE VALUES (
3, '나가사키짬뽕', '삼양', 'C', 1300, NOW() + INTERVAL 3 MONTH);
INSERT INTO NOODLE VALUES (
4, '짜파게티', '농심', 'C', 1200, NOW() + INTERVAL 3 MONTH);


SELECT * FROM NOODLE;

SET SQL_SAFE_UPDATES = 0;

SELECT PRICE/NUM FROM NOODLE;
SELECT ROUND(PRICE/NUM, -2) FROM NOODLE;
SELECT TRUNCATE(PRICE/NUM, -2) FROM NOODLE;
SELECT MOD(PRICE, NUM) FROM NOODLE;
SELECT LOWER(KIND) FROM NOODLE;
SELECT ROUND(LENGTH(NAME)/3, 0) FROM NOODLE;
SELECT SUBSTR(NAME, 2, 2) FROM NOODLE;
SELECT CONCAT(COMPANY, ' ', NAME) FROM NOODLE;
SELECT LPAD(NAME,6,'*') FROM NOODLE;
SELECT RPAD(NAME,8,'#') FROM NOODLE;
SELECT DATEDIFF(E_DATE, NOW()) FROM NOODLE;

SELECT NAME, KIND, 
	CASE KIND
		WHEN 'M' THEN '봉지라면'
        WHEN 'C' THEN '컵라면'
	END AS 종류
FROM NOODLE;

SELECT NAME, PRICE,
	CASE 
		WHEN PRICE <= 850 THEN '저가'
        WHEN PRICE > 850 THEN '고가'
	END AS 가격대
FROM NOODLE;

SELECT NAME, COMPANY,
	CASE COMPANY
		WHEN '농심' THEN '대기업'
        WHEN '오뚜기' THEN '대기업'
	ELSE '중소기업'
	END AS 기업분류
FROM NOODLE;


SELECT NAME, E_DATE,
	CASE 
		WHEN DATEDIFF(E_DATE,NOW()) <= 30 THEN '긴급'
        WHEN DATEDIFF(E_DATE,NOW()) BETWEEN 31 AND 60 THEN '주의'
        ELSE '안전'
	END AS 유통기한
FROM NOODLE;

SELECT NAME, PRICE,
	CASE WHEN PRICE <= 850 THEN '추천'
		 WHEN PRICE > 850 THEN '비추천'
	END AS 가성비,
    KIND,
	CASE KIND
		WHEN 'M' THEN '봉지라면'
        WHEN 'C' THEN '컵라면'
	END AS 종류
FROM NOODLE;

