# Generated by Django 5.1.2 on 2024-10-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_answer_athor_alter_question_athor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='athor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='athor',
            new_name='author',
        ),
        migrations.AddField(
            model_name='answer',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
